version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql # same as service name
      DATABASE_USER: 'user'
      DATABASE_PASSWORD: 'password'
      DATABASE_NAME: 'mydb'
      JWT_SECRET: 'secret'
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  my-db:
